steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/krmayankk/spinnaker-demo"]
    env: ["PROJECT_ROOT=github.com/krmayankk/spinnaker-demo"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/core-sam-poc/spinnaker-demo:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/core-sam-poc/spinnaker-demo:$REVISION_ID"
